export const labelMap = {
  "0": "accident",
  "1": "adopt",
  "2": "afraid",
  "3": "africa",
  "4": "afternoon",
  "5": "again",
  "6": "airplane",
  "7": "alarm",
  "8": "all",
  "9": "alone",
  "10": "answer",
  "11": "apple",
  "12": "argue",
  "13": "army",
  "14": "arrive",
  "15": "asl",
  "16": "aunt",
  "17": "australia",
  "18": "awful",
  "19": "awkward",
};
